name: Trigger auto deployment for capps0-snehapar-sample0

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ Main ]
    paths:
    - '**'
    - '.github/workflows/capps0-snehapar-sample0-AutoDeployTrigger-b5d11690-68c6-4e31-87df-c0e523a76b33.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAPPS0SNEHAPARSAMPLE0_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.CAPPS0SNEHAPARSAMPLE0_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPS0SNEHAPARSAMPLE0_REGISTRY_PASSWORD }}
          containerAppName: capps0-snehapar-sample0
          resourceGroup: ca-snehapar-group
          imageToBuild: snehaparacr.azurecr.io/capps0-snehapar-sample0:${{ github.sha }}
          

     

