name: Trigger auto deployment for capps-snehapar-sample2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ Main ]
    paths:
    - '**'
    - '.github/workflows/capps-snehapar-sample2-AutoDeployTrigger-0b9d140e-7e05-4185-9b77-7b31da1a1ed5.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAPPSSNEHAPARSAMPLE2_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.CAPPSSNEHAPARSAMPLE2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPSSNEHAPARSAMPLE2_REGISTRY_PASSWORD }}
          containerAppName: capps-snehapar-sample2
          resourceGroup: ca-snehapar-group
          imageToBuild: snehaparacr.azurecr.io/capps-snehapar-sample2:${{ github.sha }}
          

     

