name: Trigger auto deployment for capp-snehapar-sample91

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ Main ]
    paths:
    - '**'
    - '.github/workflows/capp-snehapar-sample91-AutoDeployTrigger-a1a6f62a-3229-4aee-a041-d4f7a78134dc.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAPPSNEHAPARSAMPLE91_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.CAPPSNEHAPARSAMPLE91_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPSNEHAPARSAMPLE91_REGISTRY_PASSWORD }}
          containerAppName: capp-snehapar-sample91
          resourceGroup: ca-snehapar-group
          imageToBuild: snehaparacr.azurecr.io/capp-snehapar-sample91:${{ github.sha }}
          

     

