name: Trigger auto deployment for capp-snehapar-sample933

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ Main ]
    paths:
    - '**'
    - '.github/workflows/capp-snehapar-sample933-AutoDeployTrigger-81dbd758-abb6-4289-a12f-de43c6df1ba6.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAPPSNEHAPARSAMPLE933_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.CAPPSNEHAPARSAMPLE933_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPSNEHAPARSAMPLE933_REGISTRY_PASSWORD }}
          containerAppName: capp-snehapar-sample933
          resourceGroup: ca-snehapar-group
          imageToBuild: snehaparacr.azurecr.io/capp-snehapar-sample933:${{ github.sha }}
          

     

