name: Trigger auto deployment for test-sample-2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ Main ]
    paths:
    - '**'
    - '.github/workflows/test-sample-2-AutoDeployTrigger-b8e33849-ed9c-4b95-995e-20dea9c0e8a8.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTSAMPLE2_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.TESTSAMPLE2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTSAMPLE2_REGISTRY_PASSWORD }}
          containerAppName: test-sample-2
          resourceGroup: ca-snehapar-group
          imageToBuild: snehaparacr.azurecr.io/test-sample-2:${{ github.sha }}
          

     

